### ISSUE TITLE
The SAX parser pull-parser conflicts with Tomcat SAX parser

### ISSUE THREAD

**Issue by cofinoa** [ESGF/esg-orp#30]
https://github.com/ESGF/esg-orp/blob/3da3bcfcd93773275f0ce2cbe89fd5459df6a261/.classpath#L99
The pull-parser library overrides the Tomcat SAX parser making the osg-orp application failing to load
```
Nov 08, 2018 2:37:10 PM org.apache.tomcat.util.descriptor.web.WebXmlParser parseWebXml
SEVERE: Parse error in application web.xml file at [file:/usr/local/apache-tomcat-8.5.34/webapps/esg-orp/WEB-INF/web.xml]
org.xml.sax.SAXNotSupportedException: not supported setting property http://xml.org/sax/properties/lexical-handler
       at org.gjt.xpp.sax2.Driver.setProperty(Driver.java:204)
       at org.apache.tomcat.util.digester.Digester.getXMLReader(Digester.java:871)
```
I have rename/removed the `pull-parser-2.jar` in the esg-orp's `WEB-INF/lib` directory and the esg-orp webapp is up and running.

**Comment by sashakames** [comment]
Fixed
